language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="mirage-types:. mirage-runtime:. mirage:. mirage-types-lwt:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="mirage-types" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-types" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-types" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-runtime" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-runtime" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-runtime" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage" OCAML_VERSION="4.06.0"
  - PACKAGE="mirage-types-lwt" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-types-lwt" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-types-lwt" OCAML_VERSION="4.06.0"
