language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
 global:
   - EXTRA_REMOTES="git://github.com/mirage/mirage-dev.git"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
 matrix:
   - PACKAGE=mirage OCAML_VERSION=4.03.0 MODE=xen
